### ISSUE TITLE
Watch option exits on error

### ISSUE THREAD

**Issue by Dash-L** [robertcorponoi/godot-rust-cli#2]
Title mostly explains it: using `godot-rust-cli build --watch` will exit if `cargo build` encounters an error, this might be intentional, however, I save a lot, especially since it is usually required to save to get rust-analyzer to do its thing, at least in my editor, so it would be nice if the error was reported, but the command did not exit, letting you continue editing and building.

**Comment by robertcorponoi** [comment]
Thank you for the issue, I will look into this and fix it promptly.

**Comment by robertcorponoi** [comment]
This should be fixed on version 0.1.3, sorry for the delay.

**Comment by Dash-L** [comment]
No problem, thanks so much!
